# I have taken this from redis. Please see this link for license information:
# https://github.com/antirez/redis
# Top level makefile, the real shit is at src/Makefile

default: all

.DEFAULT:
	cd src && $(MAKE) $@

install:
	cd src && $(MAKE) $@

.PHONY: install
